/**
 * ╔══════════════════════════════════════════════════════════╗
 * ║  URO — System Prompt Builder                             ║
 * ║  Combines persona + guardrails + response config          ║
 * ║  into a coherent system instruction for the AI model      ║
 * ╚══════════════════════════════════════════════════════════╝
 *
 * DO NOT edit this file for personality changes — edit the
 * config files (persona.ts, guardrails.ts, response.ts) instead.
 */

import { persona } from "./persona";
import { guardrails } from "./guardrails";
import { responseConfig } from "./response";

/**
 * Builds the full system prompt injected into every AI call.
 * @param userName - The display name of the user being talked to.
 * @returns The system instruction string.
 */
export function buildSystemPrompt(userName: string): string {
  const sections: string[] = [];

  // ─── IDENTITY ──────────────────────────────────────────────
  sections.push(`# Identity
You are ${persona.name}. ${persona.identity}
${persona.backstory}`);

  // ─── PERSONALITY ───────────────────────────────────────────
  sections.push(`# Personality Traits
${persona.personality.map((trait) => `- ${trait}`).join("\n")}`);

  // ─── LANGUAGE & STYLE ─────────────────────────────────────
  sections.push(`# Language & Style
- Language: ${persona.languageStyle}
- Tone: ${responseConfig.tone}
- Reply style: ${responseConfig.replyStyle}
- Use emojis: ${persona.useEmojis ? "yes, naturally" : "no"}
- Use Discord markdown formatting: ${responseConfig.useMarkdown ? "yes" : "no"}
- Max response length: ~${responseConfig.maxResponseLength} characters. If longer, split into logical sections.`);

  // ─── MUST DO ───────────────────────────────────────────────
  if (persona.mustDo.length > 0) {
    sections.push(`# You MUST
${persona.mustDo.map((rule) => `- ${rule}`).join("\n")}`);
  }

  // ─── MUST NOT ──────────────────────────────────────────────
  if (persona.mustNot.length > 0) {
    sections.push(`# You MUST NOT
${persona.mustNot.map((rule) => `- ${rule}`).join("\n")}`);
  }

  // ─── GUARDRAILS ────────────────────────────────────────────
  sections.push(`# Safety Rules (NEVER violate these)
${guardrails.rules.map((rule) => `- ${rule}`).join("\n")}`);

  // ─── BLOCKED TOPICS ────────────────────────────────────────
  if (guardrails.blockedTopics.length > 0) {
    sections.push(`# Blocked Topics (DO NOT discuss under any circumstances)
${guardrails.blockedTopics.map((topic) => `- ${topic}`).join("\n")}
If a user asks about these topics, politely decline and redirect the conversation.`);
  }

  // ─── EXAMPLE RESPONSES ────────────────────────────────────
  if (persona.exampleResponses.length > 0) {
    sections.push(`# Example Response Style
${persona.exampleResponses.map((ex) => `"${ex}"`).join("\n")}`);
  }

  // ─── CONTEXT ───────────────────────────────────────────────
  sections.push(`# Current Context
- You are talking to: ${userName}
- Platform: Discord server
- You will receive recent channel history for conversation context.
- Always be aware of the ongoing conversation — don't repeat what was just said.`);

  return sections.join("\n\n");
}
